### ISSUE TITLE
Reverse engineer existing environment

### ISSUE THREAD

**Issue by buzzedword** [dnerdy/namesync#1]
Curious to see if this tool could also be used to reverse engineer an existing DNS environment to the file structure you're looking for. One of my CloudFlare accounts has hundreds of records, would be awesome to codify them at once.

**Comment by dnerdy** [comment]
This isn't exposed, though it would be quite simple to add. There's a function named `records_to_flatfile` in `records.py`, and `CloudFlareBackend.records()` returns records from the API.

Something to keep in mind in that paging support isn't implemented for the Cloudflare API. This sounds like an issue you could run into.

Are you interested in helping add this feature?

I think a `--get` option that outputs the records to stdout would be good.

**Comment by buzzedword** [comment]
Yeah, I'd be down to give it a shot. I think I have enough information to work it out. Thanks for the pointers.
